[package]
name = "gitwrapper_blockchain_release"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]


[dependencies]
solana-program = "=1.18.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"